### ISSUE TITLE
Reproducibility instructions

### ISSUE THREAD

**Issue by gogolgrind** [yun-kwak/efficient-mcts#1]
Hello!

Thank you for uploading the efficient-mcts code. However, it appears that the current version is not reproducible. For example, the imports for pine module (which seems to be a custom-written package) looks like to be broken, and the atari.py module is missing.

Could you please provide suggestions on how to resolve these issues to run the code quickly and successfully? Also, could you let us know approximately when we can expect a working version?

Thank you in advance!

**Comment by yun-kwak** [comment]
Hi! I apologize for the inconvenience you experienced. We've fixed the errors and added instructions for running the experiments in the README.md file.
If you encounter any further problems or have questions, please let me know! 🙂
